###
### INPUTS FOR THE MONTE-CARLO APPROACH GIVEN IN SCRIPTS/TEST.PY
###

monte_carlo:
    pypsa_standard:
      # as key: add below the pypsa object for the monte_carlo sampling, "network" is only allowed for filtering!
      # as value: currently supported format [l_bound, u_bound] or empty [], represent multiplication factors for the object
      # TODO: Support also probability inputs for Monte-Carlo e.g. [l_bound, u_bound, zeta, gamma, distribution_type]
      # TODO: Support inputs to simulate outages biggest lines "lines.p_nom_opt.max(): [-3000MW 0MW]""
      # TODO: Support inputs to simulate outages of biggest power plant "generators.p_nom.max()": [-1000MW 0MW]
      loads_t.p_set: [0.9, 1.1]
      generators_t.p_max_pu.loc[:, network.generators.carrier == "wind"]: [0.5, 1.2]
      generators_t.p_max_pu.loc[:, network.generators.carrier == "solar"]: [0.5, 2]
      # ... user can add here flexibly more features for the Monte-Carlo sampling
    options:
      samples: 169  # number of optimizations
      sampling_strategy: "chaospy"  # "pydoe2", "chaospy", "scipy", packages that are supported

